name: "SonarQube Analysis"
description: "Run SonarQube analysis with quality gate check"

inputs:
  sonar-token:
    description: "SonarQube authentication token"
    required: true
  sonar-host-url:
    description: "SonarQube server URL"
    required: true
  quality-gate-timeout:
    description: "Quality gate timeout in minutes"
    required: false
    default: "5"
  project-key:
    description: "SonarQube project key"
    required: true
  project-name:
    description: "SonarQube project name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Sonar analyzers
      uses: actions/cache@v4
      with:
        path: $HOME/.sonar/cache
        key: sonar-analyzers-${{ runner.os }}-${{ inputs.sonar-host-url }}-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          sonar-analyzers-${{ runner.os }}-${{ inputs.sonar-host-url }}-
          sonar-analyzers-${{ runner.os }}-

    - name: Build and analyze
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        SONAR_USER_HOME: $HOME/.sonar
        SONAR_PROJECT_KEY: ${{ inputs.project-key }}
        SONAR_PROJECT_NAME: ${{ inputs.project-name }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.project-key }} -Dsonar.projectName='${{ inputs.project-name }}'
