name: "Semantic Release"
description: "Run semantic release to create tags and releases"

inputs:
  github-token:
    description: "GitHub token for creating releases"
    required: true
  release-command:
    description: "Command to run semantic release"
    required: false
    default: "npx semantic-release"
  working-directory:
    description: "Working directory for the release"
    required: false
    default: "."
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js Environment
      uses: SKILL-FAMILIAR-PJ/devops-template/actions/common/setup/node@main
      if: ${{ inputs.node-version != '' }}
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"
        install-command: yarn install --immutable

    - name: Semantic Release
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        HUSKY: 0
      run: ${{ inputs.release-command }}
