name: "Setup Node.js Environment"
description: "Setup Node.js with caching and install dependencies"

inputs:
  java-version:
    description: "Java version"
    required: false
    default: "21"
  jdk-distribution:
    description: "JDK distribution to use (e.g., temurin, zulu, corretto)"
    required: false
    default: "corretto"
  install-command:
    description: "Package installation command"
    required: false
    default: "mvn install -DskipTests"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.jdk-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: maven

    - name: Install dependencies
      shell: bash
      run: ${{ inputs.install-command }}
